### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by fly2hi** [Agha-Shadi/msgforwarder#2]
Hello 
I am running the script on Windows
It’s running fine but sometimes I have connections errors on my computer
Is there a way to make the script rerun after connection error? The connection is usually restored after 2 minutes

thanks 

Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Automatic reconnection failed 5 time(s)
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection to Telegram failed 5 time(s)')>
ConnectionError: Connection to Telegram failed 5 time(s)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 432, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\forwordbot\MsgForwarder.py", line 24, in <module>
    client.run_until_disconnected()
  File "C:\Program Files\Python310\lib\site-packages\telethon\client\updates.py", line 84, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Program Files\Python310\lib\site-packages\telethon\client\updates.py", line 29, in _run_until_disconnected
    return await self.disconnected
ConnectionError: Connection to Telegram failed 5 time(s)
PS C:\forwordbot> python MsgForwarder.py

**Comment by M4K14** [comment]
Since you are on windows, the cleanest and most robust way to handle this is to use a simple Windows Batch script wrapper. This way, if the Python script crashes, Windows will notice, wait for your connection to return, and launch it right back up. Changing the main code to do it is not appropriate, since there are always some other people needing it to be disconnected in such scenarios.

```
@echo off
:loop
echo [%date% %time%] Starting msgforwarder...
python MsgForwarder.py

echo [%date% %time%] Script crashed or disconnected. Waiting 2 minutes before restarting...
:: Choice acts as a reliable sleep timer in Windows (120 seconds)
choice /d y /t 120 > nul

echo [%date% %time%] Attempting to reconnect...
goto loop
```

save the file as `run_bot.bat` inside the exact same folder where `MsgForwarder.py` is located
